### ISSUE TITLE
re render parent.

### ISSUE THREAD

**Issue by kapilpipaliya** [rturnq/solid-router#9]
When I navigate from one route to another route, it unnecessary re-render parent component.

**Comment by rturnq** [comment]
Without a code example, I'm not sure exactly what you are seeing; however, I played around with a couple patterns and was able to produce unnecessary remounting when using the function form of a route (ie. using the `render` prop).

It looks like this is due to the fact I am passing values to the render function instead of the signals. Originally I just wanted really easy access to those values but it is really antithetical to the way solid works. I hadn't really considered it at the time but basically the render function wrapper was subscribing to all of the parameters which causes the render function to execute any time there is a route change.

In order to solve this issue I'm going to have to pass in the signal getters instead of the values as parameters to the render function which will be a breaking change. This would make it align more closely to using the `useRoute` "hook" in a component. I might also take this opportunity to change additional things. For instance I was thinking about removing the render property all together and making children so it could either be a function or a JSX element.

**Comment by kapilpipaliya** [comment]
I have `OrgLayout` component which has this code:
```
        <Switch>
          <Match when={state.isLoading}>Loading...</Match>
          <Match when={!state.authorized}>{state.er}</Match>
          <Match when={state.fetch_data}>
            <Switch>
              <MatchRoute path="/organization/:org" render={OrgIndex} />
              <MatchRoute path="/organization/:org/index" render={OrgIndex} />
              <MatchRoute path="/organization/:org/project/:project" render={ProjectLayout} />
            </Switch>
          </Match>
        </Switch>
```
When i navigate between `organization` routes it re fetch data and I see `Loading...` on the screen.

**Comment by kapilpipaliya** [comment]
I am fetching data in `OrgLayout` component. i changed to `useRoute` and used children pattern instead of `render` function. It works.


but if I add this code in  `OrgLayout`  it still refetch data when changing route, when `getParmas` is not changed:
```js
 const { getParams } = useRoute();
  createEffect(() => {
      if (getParams().org) {
        reFetch();
      }
  });
```

**Comment by kapilpipaliya** [comment]
I have links for path '/' and '/contact` when '/contact' is active, it also highlight '/'.

**Comment by kapilpipaliya** [comment]
I am waiting for `<NavLink/>` component fix so it match full path.
do you fix this until you release next major version?

**Comment by rturnq** [comment]
This behavior is intended and configurable using the `end` property which is available on `NavLink`, `ShowRoute` and `MatchRoute` components. By default (end == false), their path will match against all child paths. By setting `end` to `true` you can tell the component you want it to only match that path and not any child paths.

Here is an example: https://codesandbox.io/s/rturnq-solid-router-nav-link-ytg9x

You'll see that with `end` set to true to the home link, so it will only be active when the path is '/'. Also, notice I have end on the `MatchRoute` for home which means it only matches the '/' path and lets '/baz' through to the switch's fallback.

**Comment by kapilpipaliya** [comment]
Thank you so much. It solved the problem.
